 <?php

 $title = 'Add new post';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('blog', array('action' => 'add')));
 $form->prepare();
                         
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id')) . '<br />';
 echo $this->formRow($form->get('title')) . '<br />';
 echo $this->formRow($form->get('author')) . '<br />';
 echo $this->formRow($form->get('content')) . '<br />';
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();  
                     