 <?php

 $title = 'My blog';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('blog', array('action'=>'add'));?>">Add new post</a>
 </p>

 <table class="table">
 <tr>
 
     <th><?php echo $this->escapeHtml($post->title);?></th>
     <th>&nbsp;</th>
 </tr>
 <tr>     
     <td>
  
             
    
     </td>
     <td>Author:&nbsp;<?php echo $this->escapeHtml($post->author);?></td>
     
 <tr>
     <td>
     
      <?php echo $this->escapeHtml($post->content);?>
    </td>
    <th>&nbsp;</th>
 </tr>
 <tr>
     <td>     
         <a href="<?php echo $this->url('blog',
             array('action'=>'edit', 'id' => $post->id));?>">Edit</a>
         <a href="<?php echo $this->url('blog',
             array('action'=>'delete', 'id' => $post->id));?>">Delete</a>
    </td>
    <th>&nbsp;</th>
 </tr>             
     </td>
 </tr>
 </table>
